# Generated by Django 4.2.1 on 2023-06-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_number', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
