# Generated by Django 4.2.1 on 2023-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_options_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品番号'),
        ),
    ]
