# Generated by Django 4.2.1 on 2023-06-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_image_remove_product_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asuraku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='あす楽'),
        ),
    ]
